spring.application.name=user-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.datasource.url=jdbc:postgresql://localhost:5432/mydoctor_user_service
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
server.port=8081
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=haritiasmae@gmail.com
spring.mail.password=jhzj giqv iqnn pzrq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=haritiasmae@gmail.com

logging.level.org.springframework.security=DEBUG
logging.level.ma.hariti.asmaa.mydoctor.userservice=DEBUG