apiVersion: v1
kind: ConfigMap
metadata:
  name: mydoctor-config
data:
  EUREKA_URL: "http://discovery-server:8761/eureka/"
  FRONTEND_URL: "http://a6da61e1b5ae14789ac19ae750caa5ff-1349906051.eu-west-3.elb.amazonaws.com"
  API_URL: "http://a27e9e956a78240589a9b19fa98b03f6-1917442781.eu-west-3.elb.amazonaws.com"
  DB_HOST: "postgres"
  AWS_REGION: "eu-west-3"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
  S3_BUCKET: "mydoctor-recordings-prod"
  S3_TRANSCRIPT_BUCKET: "mydoctor-transcripts-prod"
  SQS_QUEUE: "transcription-queue-prod"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  config.json: |
    {
      "apiUrl": "http://a27e9e956a78240589a9b19fa98b03f6-1917442781.eu-west-3.elb.amazonaws.com"
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: mydoctor-secrets
type: Opaque
stringData:
  AWS_ACCESS_KEY: "AKIAV6KYCYNJXOMDPN5Q"
  AWS_SECRET_KEY: "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"
  DB_PASSWORD: "postgres"
  MAIL_USERNAME: "haritiasmae@gmail.com"
  MAIL_PASSWORD: "jhzj giqv iqnn pzrq"
  JWT_SECRET_KEY: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
