apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-service
  template:
    metadata:
      labels:
        app: doctor-service
    spec:
      containers:
        - name: doctor-service
          image: REPLACE_WITH_YOUR_ACCOUNT.dkr.ecr.eu-west-3.amazonaws.com/mydoctor-doctor-service:latest
          ports:
            - containerPort: 8084
          env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: mydoctor-config
                  key: EUREKA_URL
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/mydoctor_user_service" # Shared DB or update if separate
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mydoctor-secrets
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: doctor-service
spec:
  ports:
    - port: 8084
  selector:
    app: doctor-service
