apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
        - name: patient-service
          image: 408743494483.dkr.ecr.eu-west-3.amazonaws.com/mydoctor-patient-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: mydoctor-config
                  key: EUREKA_URL
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: mydoctor-config
                  key: EUREKA_INSTANCE_PREFER_IP_ADDRESS
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/mydoctor_patient_service"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mydoctor-secrets
                  key: DB_PASSWORD
            - name: APP_FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: mydoctor-config
                  key: FRONTEND_URL
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
spec:
  ports:
    - port: 8083
  selector:
    app: patient-service
