apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: REPLACE_WITH_YOUR_ACCOUNT.dkr.ecr.eu-west-3.amazonaws.com/mydoctor-user-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: mydoctor-config
                  key: EUREKA_URL
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/mydoctor_user_service"
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
    - port: 8081
  selector:
    app: user-service
