server.port=8085
spring.application.name=medicalrecord-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.datasource.url=jdbc:postgresql://localhost:5432/mydoctor_medicalrecord_service
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# Increase file upload size limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# AWS Configuration
aws.access-key=AKIAV6KYCYNJXOMDPN5Q
aws.secret-key=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
aws.region=eu-west-3
aws.s3.bucket=mydoctor-recordings
aws.sqs.queue-name=transcription-queue
